

name: 💅 Build and check code style

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.10", "3.11"]

    steps:
      - name: ruff-action
        uses: astral-sh/ruff-action@v3.2.0
